# File adapted from https://github.com/vfarcic/argo-combined-demo
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mydjangowebsite-github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    mydjangowebsite:
      owner: randommm
      repository: mydjangowebsite
      webhook:
        endpoint: /mydjangowebsite
        port: "12000"
        method: POST
        url: http://webhook.20.0.160.116.nip.io
      events:
        - "*"
      apiToken:
        name: mydjangowebsite-github-access
        key: token
      insecure: true
      active: true
      contentType: json

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydjangowebsite-github
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /mydjangowebsite
        pathType: Prefix
        backend:
          service:
           name: mydjangowebsite-github-eventsource-svc
           port:
             number: 12000
    host: webhook.20.0.160.116.nip.io
