apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
namespace: staging
images:
  - name: marcoinacio/mydjangowebsite
    newTag: "a897d09c02f6701f6e2429871d84d0180590e545"
